// Generated by `npm run mascots:sync` from assets/mascots/ — do not edit by hand.
import type { ImageSourcePropType } from "react-native";

import type { Mood, PeekLook, PeekPose, Species, WalkFrame } from "./art";

export const MASCOT_IMAGES: Partial<Record<Species, Partial<Record<Mood, ImageSourcePropType>>>> = {
  goose: {
    reading: require("../../../assets/mascots/goose/reading.png"),
    sleepy: require("../../../assets/mascots/goose/sleepy.png"),
    celebrating: require("../../../assets/mascots/goose/celebrating.png"),
    confused: require("../../../assets/mascots/goose/confused.png"),
    scanning: require("../../../assets/mascots/goose/scanning.png"),
  },
  duckling: {
    reading: require("../../../assets/mascots/duckling/reading.png"),
    sleepy: require("../../../assets/mascots/duckling/sleepy.png"),
    celebrating: require("../../../assets/mascots/duckling/celebrating.png"),
    confused: require("../../../assets/mascots/duckling/confused.png"),
    scanning: require("../../../assets/mascots/duckling/scanning.png"),
  },
};

export const PEEK_IMAGES: Partial<Record<PeekLook, Partial<Record<PeekPose, ImageSourcePropType>>>> = {
  goose: {
    rest: require("../../../assets/mascots/goose-peek/rest.png"),
    honk: require("../../../assets/mascots/goose-peek/honk.png"),
    blink: require("../../../assets/mascots/goose-peek/blink.png"),
    suspicious: require("../../../assets/mascots/goose-peek/suspicious.png"),
    wink: require("../../../assets/mascots/goose-peek/wink.png"),
    steal: require("../../../assets/mascots/goose-peek/steal.png"),
  },
  duckling: {
    rest: require("../../../assets/mascots/duckling-peek/rest.png"),
    honk: require("../../../assets/mascots/duckling-peek/honk.png"),
    blink: require("../../../assets/mascots/duckling-peek/blink.png"),
    suspicious: require("../../../assets/mascots/duckling-peek/suspicious.png"),
    wink: require("../../../assets/mascots/duckling-peek/wink.png"),
    steal: require("../../../assets/mascots/duckling-peek/steal.png"),
    wave: require("../../../assets/mascots/duckling-peek/wave.png"),
  },
  "duckling-wings": {
    rest: require("../../../assets/mascots/duckling-wings-peek/rest.png"),
    honk: require("../../../assets/mascots/duckling-wings-peek/honk.png"),
    blink: require("../../../assets/mascots/duckling-wings-peek/blink.png"),
    suspicious: require("../../../assets/mascots/duckling-wings-peek/suspicious.png"),
    wink: require("../../../assets/mascots/duckling-wings-peek/wink.png"),
    steal: require("../../../assets/mascots/duckling-wings-peek/steal.png"),
    wave: require("../../../assets/mascots/duckling-wings-peek/wave.png"),
  },
};

export const WALK_IMAGES: Partial<Record<Species, Partial<Record<WalkFrame, ImageSourcePropType>>>> = {
  goose: {
    "step-1": require("../../../assets/mascots/goose-walk/step-1.png"),
    "step-2": require("../../../assets/mascots/goose-walk/step-2.png"),
  },
  duckling: {
    "step-1": require("../../../assets/mascots/duckling-walk/step-1.png"),
    "step-2": require("../../../assets/mascots/duckling-walk/step-2.png"),
  },
};
