// Generated by `npm run mascots:sync` from assets/mascots/ — do not edit by hand.
import type { ImageSourcePropType } from "react-native";

import type { PeekPose } from "./art";
import type { Mood, Species } from "./shapes";

export const MASCOT_IMAGES: Partial<Record<Species, Partial<Record<Mood, ImageSourcePropType>>>> = {
  goose: {
    reading: require("../../../assets/mascots/goose/reading.png"),
  },
};

export const PEEK_IMAGES: Partial<Record<PeekPose, ImageSourcePropType>> = {};
