// Generated by `npm run mascots:sync` from assets/mascots/ — do not edit by hand.
import type { ImageSourcePropType } from "react-native";

import type { Mood, PeekPose, WalkFrame } from "./art";

export const MASCOT_IMAGES: Partial<Record<Mood, ImageSourcePropType>> = {
  reading: require("../../../assets/mascots/goose/reading.png"),
  sleepy: require("../../../assets/mascots/goose/sleepy.png"),
  celebrating: require("../../../assets/mascots/goose/celebrating.png"),
  confused: require("../../../assets/mascots/goose/confused.png"),
  scanning: require("../../../assets/mascots/goose/scanning.png"),
};

export const PEEK_IMAGES: Partial<Record<PeekPose, ImageSourcePropType>> = {
  rest: require("../../../assets/mascots/goose-peek/rest.png"),
  honk: require("../../../assets/mascots/goose-peek/honk.png"),
  blink: require("../../../assets/mascots/goose-peek/blink.png"),
  suspicious: require("../../../assets/mascots/goose-peek/suspicious.png"),
  wink: require("../../../assets/mascots/goose-peek/wink.png"),
  steal: require("../../../assets/mascots/goose-peek/steal.png"),
};

export const WALK_IMAGES: Partial<Record<WalkFrame, ImageSourcePropType>> = {
  "step-1": require("../../../assets/mascots/goose-walk/step-1.png"),
  "step-2": require("../../../assets/mascots/goose-walk/step-2.png"),
};
