/**
 * Registers the drawn mascot PNGs for the app: checks them, then writes
 * src/components/mascot/images.generated.ts with static requires (Metro can't require dynamically).
 *
 *   npm run mascots:sync   (also runs as part of `npm run mascots`)
 */
import fs from "node:fs";

import { ART_SETS, isUsable, root, scanArt, type ArtFile } from "./mascot-art.ts";

const scan = scanArt();
const target = new URL("src/components/mascot/images.generated.ts", root);
const req = (path: string) => `require("../../../${path}")`;

const TYPES = { moods: "Mood", peek: "PeekPose", walk: "WalkFrame" } as const;
const EXPORTS = { moods: "MASCOT_IMAGES", peek: "PEEK_IMAGES", walk: "WALK_IMAGES" } as const;

const blocks = ART_SETS.map((set) => {
  const files = scan[set.key] as Partial<Record<string, ArtFile>>;
  const lines = set.names.flatMap((name) => {
    const file = files[name];
    const key = /^[a-z]\w*$/i.test(name) ? name : JSON.stringify(name);
    return file && isUsable(file) ? [`  ${key}: ${req(file.path)},`] : [];
  });
  const body = lines.length ? `\n${lines.join("\n")}\n` : "";
  return `export const ${EXPORTS[set.key]}: Partial<Record<${TYPES[set.key]}, ImageSourcePropType>> = {${body}};`;
});

const source = `// Generated by \`npm run mascots:sync\` from assets/mascots/ — do not edit by hand.
import type { ImageSourcePropType } from "react-native";

import type { Mood, PeekPose, WalkFrame } from "./art";

${blocks.join("\n\n")}
`;

const previous = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
if (previous !== source) fs.writeFileSync(target, source);

const counts = ART_SETS.map((set) => {
  const drawn = set.names.filter((name) => (scan[set.key] as Partial<Record<string, ArtFile>>)[name]).length;
  return `${set.folder}: ${drawn}/${set.names.length}`;
});
const blocked = ART_SETS.flatMap((set) => Object.values(scan[set.key] as Record<string, ArtFile>)).filter((f) => !isUsable(f));
console.log(`Drawn — ${counts.join(" · ")}`);
if (blocked.length) console.log(`Not used in the app yet (background not removed):\n${blocked.map((f) => `  - ${f.path}`).join("\n")}`);
if (scan.missing.length) console.log(`Still to draw:\n${scan.missing.map((m) => `  - ${m}`).join("\n")}`);
if (scan.warnings.length) console.log(`\nWarnings:\n${scan.warnings.map((w) => `  ! ${w}`).join("\n")}`);
console.log(previous === source ? "Image registry unchanged." : "Updated src/components/mascot/images.generated.ts");
