/**
 * Registers the drawn mascot PNGs for the app: checks them, then writes
 * src/components/mascot/images.generated.ts with static requires (Metro can't require dynamically).
 *
 *   npm run mascots:sync   (also runs as part of `npm run mascots`)
 */
import fs from "node:fs";

import { ART_KINDS, ART_SETS } from "../src/components/mascot/art.ts";
import { isUsable, root, scanArt, type ArtFile } from "./mascot-art.ts";

const scan = scanArt();
const target = new URL("src/components/mascot/images.generated.ts", root);
const req = (path: string) => `require("../../../${path}")`;
const key = (name: string) => (/^[a-z]\w*$/i.test(name) ? name : JSON.stringify(name));

/** Export name and TypeScript key types per kind (pop-ups are keyed by look, the rest by character). */
const EXPORTS = {
  moods: { name: "MASCOT_IMAGES", owner: "Species", image: "Mood" },
  peek: { name: "PEEK_IMAGES", owner: "PeekLook", image: "PeekPose" },
  walk: { name: "WALK_IMAGES", owner: "Species", image: "WalkFrame" },
} as const;

const blocks = ART_KINDS.map(({ kind }) => {
  const sets = ART_SETS.filter((set) => set.kind.kind === kind).flatMap((set) => {
    const files = scan.art[kind][set.look] ?? {};
    const lines = [...set.kind.names, ...set.kind.optional].flatMap((name) => {
      const file = files[name];
      return file && isUsable(file) ? [`    ${key(name)}: ${req(file.path)},`] : [];
    });
    return lines.length ? [`  ${key(set.look)}: {\n${lines.join("\n")}\n  },`] : [];
  });
  const { name, owner, image } = EXPORTS[kind];
  const body = sets.length ? `\n${sets.join("\n")}\n` : "";
  return `export const ${name}: Partial<Record<${owner}, Partial<Record<${image}, ImageSourcePropType>>>> = {${body}};`;
});

const source = `// Generated by \`npm run mascots:sync\` from assets/mascots/ — do not edit by hand.
import type { ImageSourcePropType } from "react-native";

import type { Mood, PeekLook, PeekPose, Species, WalkFrame } from "./art";

${blocks.join("\n\n")}
`;

const previous = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
if (previous !== source) fs.writeFileSync(target, source);

const counts = ART_SETS.map((set) => {
  const files = scan.art[set.kind.kind][set.look] ?? {};
  const drawn = set.kind.names.filter((name) => files[name]).length;
  const extras = set.kind.optional.filter((name) => files[name]);
  return `${set.folder} ${drawn}/${set.kind.names.length}${extras.length ? ` +${extras.join(", ")}` : ""}`;
});
const found = ART_SETS.flatMap((set) => Object.values(scan.art[set.kind.kind][set.look] ?? {})) as ArtFile[];
const blocked = found.filter((f) => !isUsable(f));
console.log(`Drawn — ${counts.join(" · ")}`);
if (blocked.length) console.log(`Not used in the app yet (background not removed):\n${blocked.map((f) => `  - ${f.path}`).join("\n")}`);
if (scan.missing.length) console.log(`Still to draw: ${scan.missing.length} images (see docs/mascot-art-brief.md)`);
if (scan.warnings.length) console.log(`\nWarnings:\n${scan.warnings.map((w) => `  ! ${w}`).join("\n")}`);
console.log(previous === source ? "Image registry unchanged." : "Updated src/components/mascot/images.generated.ts");
