/**
 * Registers the drawn mascot PNGs for the app: checks them, then writes
 * src/components/mascot/images.generated.ts with static requires (Metro can't require dynamically).
 *
 *   npm run mascots:sync   (also runs as part of `npm run mascots`)
 */
import fs from "node:fs";

import { PEEK_POSES } from "../src/components/mascot/art.ts";
import { MOODS, SPECIES } from "../src/components/mascot/shapes.ts";
import { isUsable, root, scanArt } from "./mascot-art.ts";

const scan = scanArt();
const target = new URL("src/components/mascot/images.generated.ts", root);
const req = (path: string) => `require("../../../${path}")`;

const speciesLines = SPECIES.flatMap(({ value }) => {
  const moods = MOODS.filter((m) => { const f = scan.mascots[value]?.[m]; return f && isUsable(f); });
  if (moods.length === 0) return [];
  return [`  ${value}: {\n${moods.map((m) => `    ${m}: ${req(scan.mascots[value]![m]!.path)},`).join("\n")}\n  },`];
});
const peekLines = PEEK_POSES.filter((p) => { const f = scan.peek[p]; return f && isUsable(f); }).map((p) => `  ${p}: ${req(scan.peek[p]!.path)},`);

const source = `// Generated by \`npm run mascots:sync\` from assets/mascots/ — do not edit by hand.
import type { ImageSourcePropType } from "react-native";

import type { PeekPose } from "./art";
import type { Mood, Species } from "./shapes";

export const MASCOT_IMAGES: Partial<Record<Species, Partial<Record<Mood, ImageSourcePropType>>>> = {${
  speciesLines.length ? `\n${speciesLines.join("\n")}\n` : ""
}};

export const PEEK_IMAGES: Partial<Record<PeekPose, ImageSourcePropType>> = {${peekLines.length ? `\n${peekLines.join("\n")}\n` : ""}};
`;

const previous = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
if (previous !== source) fs.writeFileSync(target, source);

const drawnMoods = MOODS.filter((m) => scan.mascots.goose?.[m]).length;
const drawnPoses = PEEK_POSES.filter((p) => scan.peek[p]).length;
const blocked = [...Object.values(scan.mascots.goose ?? {}), ...Object.values(scan.peek)].filter((f) => f && !isUsable(f));
console.log(`Goose moods: ${drawnMoods}/${MOODS.length} drawn · Peek poses: ${drawnPoses}/${PEEK_POSES.length} drawn`);
if (blocked.length) console.log(`Not used in the app yet (background not removed):\n${blocked.map((f) => `  - ${f!.path}`).join("\n")}`);
if (scan.missing.length) console.log(`Still to draw:\n${scan.missing.map((m) => `  - ${m}`).join("\n")}`);
if (scan.warnings.length) console.log(`\nWarnings:\n${scan.warnings.map((w) => `  ! ${w}`).join("\n")}`);
console.log(previous === source ? "Image registry unchanged." : "Updated src/components/mascot/images.generated.ts");
